WebLibMVC/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceMVC.ServiceManager;
using WebLibMVC.ViewModels;

namespace WebLibMVC.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IServiceManager _service;
        public AuthorsController(IServiceManager serviceManager) =>
            _service = serviceManager ?? throw new ArgumentNullException(nameof(serviceManager));

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {

            var authors = await _service.AuthorService.GetAllAuthorsAsync();
            return View(authors);
        }
        public async Task<IActionResult> GetAuthor(int id)
        {
            var authors = await _service.AuthorService.GetAuthorAsync(id);
            return View(authors);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorViewModel author)
        {
            if (ModelState.IsValid)
                await _service.AuthorService.AddAuthorAsync(author);
            else
                return Create();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var author = await _service.AuthorService.GetAuthorAsync(id);

            if (author == null)
                return NotFound();

            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AuthorViewModel author)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.AuthorService.UpdateAuthorAsync(author, id);
                }
                catch (HttpRequestException)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while updating the Author.");
                }
            }
            else
            {
                return await Edit(id);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var author = await _service.AuthorService.GetAuthorAsync(id);

            if (author == null)
                return NotFound();

            return View(author);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool isSuccessful = await _service.AuthorService.DeleteAuthorAsync(id);

            if (isSuccessful)
                return RedirectToAction("Index");

            return RedirectToAction("Delete", new { id, errorMessage = "error during deletion" });
        }
    }

}

WebLibMVC/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp;
using ServiceMVC.ServiceManager;
using WebLibMVC.ViewModels;

namespace WebLibMVC.Controllers
{
    public class BooksController : Controller
    {
        private readonly IServiceManager _service;
        public BooksController(IServiceManager serviceManager) => _service = serviceManager;

        public async Task<IActionResult> Create()
        {
            var bookViewModel = new BookViewModel();

            var authors = await _service.AuthorService.GetAllAuthorsAsync();
            var genres = await _service.GenreService.GetAllGenresAsync();



            bookViewModel.Authors.AddRange(authors.Select(author => new SelectListItem
            {
                Value = author.Id.ToString(),
                Text = $"{author.FirstName} {author.LastName}"
            }));

            bookViewModel.Genres.AddRange(genres.Select(genre => new SelectListItem
            {
                Value = genre.Id.ToString(),
                Text = genre.Name
            }));

            return View(bookViewModel);
        }

        public async Task<IActionResult> Index(int pageNumber, int? maxYear, int? minYear, string? searchTerm, string? orderBy)
        {
            var (books, metadata) = await _service.BookService.GetBooksForPageAsync(pageNumber, maxYear, minYear, searchTerm, orderBy);
            ViewBag.TotalPages = metadata.TotalPages;


            foreach (var book in books)
            {
                var author = await _service.AuthorService.GetAuthorAsync(book.AuthorId);
                var genre = await _service.GenreService.GetGenreAsync(book.GenreId);
                book.AuthorName = $"{author.FirstName} {author.LastName}";
                book.GenreName = genre.Name;
            }

            return View(books);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel book)
        {
            if (ModelState.IsValid)
                await _service.BookService.AddBookAsync(book);
            else
                return await Create();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var book = await _service.BookService.GetBookAsync(id);

            if (book == null)
                return NotFound();

            var authors = await _service.AuthorService.GetAllAuthorsAsync();
            var genres = await _service.GenreService.GetAllGenresAsync();

            book.Authors.AddRange(authors.Select(author => new SelectListItem
            {
                Value = author.Id.ToString(),
                Text = $"{author.FirstName} {author.LastName}"
            }));

            book.Genres.AddRange(genres.Select(genre => new SelectListItem
            {
                Value = genre.Id.ToString(),
                Text = genre.Name
            }));

            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BookViewModel book)
        {
            if (ModelState.IsValid)
                await _service.BookService.UpdateBookAsync(book, id);
            else
                return await Edit(id);


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var book = await _service.BookService.GetBookAsync(id);

            if (book == null)
                return NotFound();

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool isSuccessful = await _service.BookService.DeleteBookAsync(id);

            if (isSuccessful)
                return RedirectToAction("Index");

            return RedirectToAction("Delete", new { id, errorMessage = "error during deletion" });
        }

        public async Task<IActionResult> GetImage(int id)
        {
            var menuItem = await _service.BookService.GetBookAsync(id);

            byte[] imageData;
            if (menuItem.Image != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    menuItem.Image.CopyTo(memoryStream);
                    imageData = memoryStream.ToArray();
                }

                return File(imageData, $"image/{menuItem.Image.FileName}");
            }

            return NotFound();
        }
    }
}

WebLibMVC/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceMVC.ServiceManager;
using WebLibMVC.ViewModels;

namespace WebLibMVC.Controllers
{
    public class GenresController : Controller
    {
        private readonly IServiceManager _service;
        public GenresController(IServiceManager serviceManager) => 
            _service = serviceManager ?? throw new ArgumentNullException(nameof(serviceManager));
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var genres = await _service.GenreService.GetAllGenresAsync();
            return View(genres);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GenreViewModel genre)
        {
            if (ModelState.IsValid)
                await _service.GenreService.AddGenreAsync(genre);
            else
                return Create();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var genre = await _service.GenreService.GetGenreAsync(id);

            if (genre == null)
                return NotFound();
            
            return View(genre);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, GenreViewModel genre)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.GenreService.UpdateGenreAsync(genre, id);
                }
                catch (HttpRequestException)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while updating the Category.");
                }
            }
            else
            {
                return await Edit(id);
            }

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var genre = await _service.GenreService.GetGenreAsync(id);

            if (genre == null)
                return NotFound();

            return View(genre);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool isSuccessful = await _service.GenreService.DeleteGenreAsync(id);

            if (isSuccessful)
                return RedirectToAction("Index");

            return RedirectToAction("Delete", new { id, errorMessage = "error during deletion" });
        }
    }
}

WebLibMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebLibMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

WebLibMVC/Controllers/ReadersController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceMVC.ServiceManager;
using WebLibMVC.ViewModels;

namespace WebLibMVC.Controllers
{
    public class ReadersController : Controller
    {
        private readonly IServiceManager _service;
        public ReadersController(IServiceManager serviceManager) =>
            _service = serviceManager ?? throw new ArgumentNullException(nameof(serviceManager));

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var readers = await _service.ReaderService.GetAllReadersAsync();
            return View(readers);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReaderViewModel reader)
        {
            if (ModelState.IsValid)
                await _service.ReaderService.AddReaderAsync(reader);
            else
                return Create();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var reader = await _service.ReaderService.GetReaderAsync(id);

            if (reader == null)
                return NotFound();

            return View(reader);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ReaderViewModel reader)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.ReaderService.UpdateReaderAsync(reader, id);
                }
                catch (HttpRequestException)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while updating the Reader.");
                }
            }
            else
            {
                return await Edit(id);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var reader = await _service.ReaderService.GetReaderAsync(id);

            if (reader == null)
                return NotFound();

            return View(reader);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool isSuccessful = await _service.ReaderService.DeleteReaderAsync(id);

            if (isSuccessful)
                return RedirectToAction("Index");

            return RedirectToAction("Delete", new { id, errorMessage = "error during deletion" });
        }
    }

}

WebLibMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="about">
    <div class="container ">
        <h1 class="heading">
            Description of the technical assignment for
            <br>
            a WEB API project
        </h1>
        <div>
            <p class="paragraph">
                This site first of all is demonstration how I have learned how to work
                with Asp net core in frontend and backend.
            </p>
            <p class="paragraph">
                This site consist of 2 project : Asp net Core Web Api (backend) Asp net
                Core Mvc (fronend)
            </p>
            <p class="paragraph">
                I have choosed the library as the subject area because I want in a future
                create similar project but with more functionality.
            </p>
            <p class="paragraph">
                In this version of site you can look through list of Books as User. But
                to manipulate with data you must login as admin, also you can login as
                moderator, but in this role you can only change existed data. In admin
                role you can create new entities, delete them and edit as well.
            </p>
        </div>
    </div>
</div>

<div class="w-layout-blockcontainer container w-container">
    <h2 class="h2">
        Minimum server requirements
    </h2>
    <p class="paragraph">
        The developed API must contain at least the following endpoints:
    </p>
    <ul role="list">
        <li>
            <p class="paragraph">
                Getting a list of users
            </p>
        </li>
        <li>
            <p class="paragraph">
                Getting a list of products of a user&#x27;s order by his Id
            </p>
        </li>
        <li>
            <p class="paragraph">
                Adding products for sale
            </p>
        </li>
        <li>
            <p class="paragraph">
                Removing products being sold
            </p>
        </li>
        <li>
            <p class="paragraph">
                Editing products for sale
            </p>
        </li>
    </ul>
</div>

<div class="w-layout-blockcontainer container w-container">
    <h2 class="h2">
        About Login
    </h2>
    <p class="paragraph">
        To get full access to all pages and functionality, log in as an
        <strong>
            administrator
        </strong>
        :
        <br>
        <em>
            Login: admin
            <br>
            Password: ForAdm1n;
        </em>
    </p>
    <p class="paragraph">
        You can also log in as a
        <strong>
            moderator
        </strong>
        , but you can only edit some data. For example, book descriptions:
        <br>
        <em>
            Login: moderator
            <br>
            Password: ForM0derator
        </em>
    </p>
</div>

<div class="w-layout-blockcontainer container w-container">
    <h2 class="h2">
        List of all available links
    </h2>
    <ul role="list">
        <li>
            <a class="paragraph" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Books" asp-action="Index" asp-route-pageNumber="1">Books</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Authors" asp-action="Index">Authors</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Genres" asp-action="Index">Genres</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Readers" asp-action="Index">Readers</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Authorize" asp-action="Logout">Logout</a>
        </li>
        <li>
            <a class="paragraph" asp-controller="Authorize" asp-action="Login">Login as admin</a>
        </li>
    </ul>
    <h2 class="h2">
        SQL
    </h2>
    <ul role="list">
        <li>
            <a class="paragraph" href="https://localhost:5001/api/sqlqueries/AuthorFirstNamesStartingWithA/">AuthorFirstNamesStartingWithA</a>
        </li>
        <li>
            <a class="paragraph" href="https://localhost:5001/api/sqlqueries/ReadersWhoHaveMoreBooksThan/2">ReadersWhoHaveMoreBooksThan</a>
        </li>
        <li>
            <a class="paragraph" href="https://localhost:5001/api/sqlqueries/Top3YearOfPublishing/">Top3YearOfPublishing</a>
        </li>
        <li>
            <a class="paragraph" href="https://localhost:5001/api/sqlqueries/EveryTakenBookFromEveryReader/">EveryTakenBookFromEveryReader</a>
        </li>
    </ul>
</div>